site_name: Jacob AWS Certification Solutions Architect Book
site_description: "Jacob's AWS Certification Solutions Architect Tutorial"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxawscsaabook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Chap1 Exam-Intro':
    - 'L1 SAA-C02 Exam Guide': 'chap1/1Exam_Guide.md'
    - 'L2 Associate SAA-C02 Exam Topics' : 'chap1/2Learning_path.md'
  - 'Chap2 Services Cheat Sheet':
    - 'L1 AWS Best Practices': 'chap2/1best_prac.md'
    - 'L2 AWS Storage & Content Delivery Cheat Sheet': 'chap2/2s3_cs.md'
    - 'L3 AWS Security & Identity Service Cheat Sheet': 'chap2/3IS_cs.md'
    - 'L4 AWS Networking Services Cheat Sheet': 'chap2/4Ns_cs.md'
    - 'L5 AWS Compute Services Cheat Sheet': 'chap2/5CS_cs.md'
    - 'L6 AWS Database Services Cheat Sheet': 'chap2/6DS_cs.md'
    - 'L7 AWS Analytics Services Cheat Sheet': 'chap2/7AS_cs.md'
    - 'L8 AWS Application Services Cheat Sheet': 'chap2/8AS_cs.md'
    - 'L9 AWS Management Tools Cheat Sheet': 'chap2/9MT_cs.md'
    - 'L10 AWS Certification Exam Cheat Sheet': 'chap2/10EXAM_cs.md'
  - 'Chap3 Networking Exam Topics':
    - 'L1 AWS Virtual Private Cloud – VPC': 'chap3/1vpc.md'
    - 'L2 AWS Bastion Host': 'chap3/2bastion.md'
    - 'L3 AWS Direct Connect – DX': 'chap3/3direct_connect.md'
    - 'L4 AWS Elastic Load Balancer – ELB': 'chap3/4ELB.md'
    - 'L5 AWS Application Load Balancer – ALB': 'chap3/5ALB.md'
    - 'L6 AWS Network Load Balancer – NLB': 'chap3/6NLB.md'
    - 'L7 AWS Classic Load Balancer vs Application Load Balancer vs Network Load Balancer': 'chap3/7EAN_LB.md'
    - 'L8 AWS ELB Monitoring': 'chap3/8elb_mon.md'
    - 'L9 AWS Certification – Route 53 Overview': 'chap3/9route53.md'
    - 'L10 AWS Route 53 Routing Policy': 'chap3/10route53_policy.md'
    - 'L11 AWS Route 53 Resolver': 'chap3/11route53_resolver.md'
    - 'L12 AWS API Gateway': 'chap3/12api_gateway.md'
    - 'L13 AWS CloudFront': 'chap3/13cloudfront.md'
    - 'L14 AWS Direct Connect – DX': 'chap3/14direct_connect.md'


repo_url: https://github.com/Chao-Xi/jxawscsaabook.git
repo_name: "jxawscsaabook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'
