site_name: Jacob AWS Certification Solutions Architect Book
site_description: "Jacob's AWS Certification Solutions Architect Tutorial"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxawscsaabook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"

repo_url: https://github.com/Chao-Xi/jxawscsaabook.git
repo_name: "jxawscsaabook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
  i18n:
    prev: 'Previous'
    next: 'Next'
